theme: jekyll-theme-slate
title: Volca Bass Custom Firmware
description: Volca Bass Custom Firmware
url: https://github.com/mpasserini/volca-bass-custom-firmware
author: mpasserini
plugins:
  - jekyll-seo-tag
analytics:
  provider               : "google-gtag"
  google:
    measurement_id          : "G-MMPJXES1N0"
    anonymize_ip         : # true, false (default)
